language: haxe

haxe:
  - 3.4.7

env:
  - TARGET=flash OPENFL=new
  - TARGET=neko  OPENFL=new
  - TARGET=cpp   OPENFL=new
  - TARGET=html5 OPENFL=new
  - TARGET=flash OPENFL=old
  - TARGET=neko  OPENFL=old
  - TARGET=cpp   OPENFL=old
  - TARGET=html5 OPENFL=old

sudo: false
dist: trusty

addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib

install:
  - haxelib dev flixel .

script:
  - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - haxe --cwd tests --run RunTravis $TARGET $OPENFL
  - kill %1
